# Generated by Django 5.2.8 on 2025-11-24 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_video', models.FileField(help_text='원본 영상 (고화질)', upload_to='videos/original/%Y/%m/%d/')),
                ('preview_video', models.FileField(blank=True, help_text='프리뷰 영상 (저화질 + 워터마크)', null=True, upload_to='videos/preview/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, help_text='썸네일', null=True, upload_to='thumbnails/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, help_text='제작자 코멘트')),
                ('is_paid', models.BooleanField(default=False, help_text='결제 완료 여부')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(help_text='제작자', on_delete=django.db.models.deletion.CASCADE, related_name='my_submissions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(help_text='의뢰', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='requests.request')),
            ],
            options={
                'verbose_name': '제출물',
                'verbose_name_plural': '제출물들',
                'db_table': 'submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
