# Generated by Django 5.2.8 on 2025-11-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='show_in_portfolio',
            field=models.BooleanField(default=True, help_text='완료된 의뢰에서 내 작품을 포트폴리오로 공개'),
        ),
    ]
