# Generated by Django 5.2.8 on 2025-11-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='익명 의뢰 여부'),
        ),
    ]
