# Generated by Django 5.2.8 on 2025-11-24 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='금액 (+면 수입, -면 지출)')),
                ('transaction_type', models.CharField(choices=[('payment', '결제 (원본 구매)'), ('earning', '수익 (제작 완료)'), ('refund', '환불'), ('bonus', '보너스')], help_text='거래 타입', max_length=20)),
                ('description', models.TextField(blank=True, help_text='거래 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(blank=True, help_text='관련 제출물', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='submissions.submission')),
                ('user', models.ForeignKey(help_text='사용자', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '거래',
                'verbose_name_plural': '거래들',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
