# Generated by Django 5.2.8 on 2025-11-24 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='한 줄 평', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(help_text='평가자 (의뢰자)', on_delete=django.db.models.deletion.CASCADE, related_name='my_reviews', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(help_text='제출물', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='submissions.submission')),
            ],
            options={
                'verbose_name': '평가',
                'verbose_name_plural': '평가들',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
