# Generated by Django 5.2.8 on 2025-11-24 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='제목', max_length=200)),
                ('concept', models.TextField(help_text='컨셉 설명')),
                ('style', models.CharField(help_text='원하는 스타일', max_length=100)),
                ('duration', models.IntegerField(help_text='희망 영상 길이 (초)')),
                ('purpose', models.TextField(help_text='영상 용도')),
                ('request_type', models.CharField(choices=[('global', '글로벌 공개'), ('specific', '특정 사용자')], default='global', help_text='의뢰 타입', max_length=20)),
                ('reward', models.IntegerField(help_text='보상 재화')),
                ('status', models.CharField(choices=[('open', '대기중'), ('in_progress', '진행중'), ('completed', '완료'), ('cancelled', '취소')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(help_text='의뢰자', on_delete=django.db.models.deletion.CASCADE, related_name='my_requests', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, help_text='특정 사용자 지정 (선택)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '의뢰',
                'verbose_name_plural': '의뢰들',
                'db_table': 'requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
